namespace ControleFinanceiroDesktop.Models.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public char EntryType { get; set; }
        public string StatementIdentifiers { get; set; } 
    }
}

//CREATE TABLE CATEGORY (
//    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    DESCRIPTION VARCHAR(255) NOT NULL,            -- descrição da categoria
//    ENTRY_TYPE CHAR(1) NOT NULL,                   -- 'F' para fixo, 'V' para variável
//    STATEMENT_IDENTIFIERS VARCHAR(5000) NOT NULL  -- identificadores do extrato, separados por PIPE
//);
