namespace ControleFinanceiroDesktop.Models.Entities
{
    public class Statement
    {
        public int Id { get; set; }
        public DateTime? TransactionDate { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal? Amount { get; set; }
        public string? Description { get; set; }
        public int? EntryId { get; set; }
        public int? StatementTypeId { get; set; }
    }
}

//CREATE TABLE STATEMENT (
//    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    TRANSACTION_DATE DATE,
//    DUE_DATE DATE,
//    AMOUNT NUMERIC(18, 2),
//    DESCRIPTION VARCHAR(255),
//    ENTRY_ID INTEGER,
//    STATEMENT_TYPE_ID INTEGER
//);
