namespace ControleFinanceiroDesktop.Models.Entities
{
    public class StatementTypes
    {
        public int Id { get; set; }
        public string? Description { get; set; }
    }
}

//CREATE TABLE STATEMENT_TYPES (
//    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    DESCRIPTION VARCHAR(255)
//);
